<?php

namespace Pagify\Core\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class MakeThemeCommand extends Command
{
    protected $signature = 'cms:make-theme {name : Theme name or slug}';

    protected $description = 'Generate Pagify frontend theme skeleton in themes/main/{slug}.';

    public function handle(): int
    {
        $input = trim((string) $this->argument('name'));

        if ($input === '') {
            $this->error('Theme name is required.');

            return self::INVALID;
        }

        $slug = Str::of($input)->slug('-')->toString();

        if ($slug === '') {
            $this->error('Unable to derive a valid theme slug from input.');

            return self::INVALID;
        }

        $directory = base_path('themes/main/'.$slug);

        if (is_dir($directory)) {
            $this->error(sprintf('Theme directory already exists: %s', $directory));

            return self::FAILURE;
        }

        File::ensureDirectoryExists($directory.'/layouts');
        File::ensureDirectoryExists($directory.'/pages');
        File::ensureDirectoryExists($directory.'/assets/js');
        File::ensureDirectoryExists($directory.'/assets/css');
        File::ensureDirectoryExists($directory.'/assets/img');
        File::ensureDirectoryExists($directory.'/lang/en');
        File::ensureDirectoryExists($directory.'/lang/vi');

        $manifest = [
            'slug' => $slug,
            'name' => Str::of($input)->headline()->toString(),
            'version' => '1.0.0',
            'description' => 'Pagify frontend theme generated by cms:make-theme.',
            'author' => 'Community',
            'render' => [
                'engine' => 'twig',
            ],
            'requires' => [
                'php' => '>=8.2',
                'laravel' => '^12.0',
            ],
            'supports' => [
                'pagify' => '^1.0',
            ],
        ];

        File::put(
            $directory.'/theme.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
        );

        $layout = <<<'TWIG'
<!doctype html>
    <html lang="{{ locale|default('en')|replace({'_': '-'}) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {{ head|raw }}
</head>
<body>
    {{ content|raw }}
</body>
</html>
TWIG;

        $page = <<<'TWIG'
{% extends 'layouts/app.twig' %}
TWIG;

        File::put($directory.'/layouts/app.twig', $layout.PHP_EOL);
        File::put($directory.'/pages/home.twig', $page.PHP_EOL);
        File::put($directory.'/lang/en/theme.php', "<?php\n\nreturn [];\n");
        File::put($directory.'/lang/vi/theme.php', "<?php\n\nreturn [];\n");

        $readme = <<<MD
# {$input}

Generated frontend theme skeleton for Pagify.

## Next steps

1. Update theme metadata in `theme.json`.
2. Customize `layouts/app.twig`.
3. Customize `pages/home.twig`.
4. Add localized strings in `lang/en/theme.php` and `lang/vi/theme.php`.
5. Use helpers in Twig: `asset_url()`, `page_url()`, `site_url()`, `t()`, `format_date()`, `setting()`.
6. Put theme static assets in `assets/js`, `assets/css`, and `assets/img`.
MD;

        File::put($directory.'/README.md', $readme.PHP_EOL);

        $this->info(sprintf('Theme skeleton created at: %s', $directory));

        return self::SUCCESS;
    }
}
