<?php

namespace Pagify\Core\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class MakeThemeCommand extends Command
{
    protected $signature = 'cms:make-theme {name : Theme name or slug}';

    protected $description = 'Generate Pagify frontend theme skeleton in themes/main/{slug}.';

    public function handle(): int
    {
        $input = trim((string) $this->argument('name'));

        if ($input === '') {
            $this->error('Theme name is required.');

            return self::INVALID;
        }

        $slug = Str::of($input)->slug('-')->toString();

        if ($slug === '') {
            $this->error('Unable to derive a valid theme slug from input.');

            return self::INVALID;
        }

        $directory = base_path('themes/main/'.$slug);

        if (is_dir($directory)) {
            $this->error(sprintf('Theme directory already exists: %s', $directory));

            return self::FAILURE;
        }

        File::ensureDirectoryExists($directory.'/pages');
        File::ensureDirectoryExists($directory.'/assets/js');
        File::ensureDirectoryExists($directory.'/assets/css');
        File::ensureDirectoryExists($directory.'/assets/img');
        File::ensureDirectoryExists($directory.'/lang/en');
        File::ensureDirectoryExists($directory.'/lang/vi');

        $manifest = [
            'slug' => $slug,
            'name' => Str::of($input)->headline()->toString(),
            'version' => '1.0.0',
            'description' => 'Pagify frontend theme generated by cms:make-theme.',
            'author' => 'Community',
            'render' => [
                'engine' => 'wsre',
            ],
            'layouts' => [],
            'requires' => [
                'php' => '>=8.2',
                'laravel' => '^12.0',
            ],
            'supports' => [
                'pagify' => '^1.0',
            ],
        ];

        File::put(
            $directory.'/theme.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
        );

        $page = [
            'version' => 1,
            'engine' => 'wsre',
            'head' => [
                [
                    'tag' => 'meta',
                    'attrs' => ['charset' => 'utf-8'],
                ],
                [
                    'tag' => 'meta',
                    'attrs' => [
                        'name' => 'viewport',
                        'content' => 'width=device-width, initial-scale=1',
                    ],
                ],
                [
                    'tag' => 'title',
                    'text' => Str::of($input)->headline()->toString(),
                ],
            ],
            'body' => [
                [
                    'tag' => 'main',
                    'attrs' => ['data-source' => 'wsre-home'],
                    'children' => [
                        [
                            'tag' => 'section',
                            'children' => [
                                ['tag' => 'h1', 'text' => Str::of($input)->headline()->toString()],
                                ['tag' => 'p', 'text' => 'WSRE home page generated by cms:make-theme.'],
                            ],
                        ],
                    ],
                ],
            ],
        ];

        File::put(
            $directory.'/pages/home.json',
            json_encode($page, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
        );

        File::put(
            $directory.'/assets/css/app.css',
            "/* {$slug} theme styles */\n" .
            "body {\n" .
            "  margin: 0;\n" .
            "  font-family: system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, sans-serif;\n" .
            "  color: #0f172a;\n" .
            "  background: #f8fafc;\n" .
            "}\n" .
            "\n" .
            "main {\n" .
            "  max-width: 960px;\n" .
            "  margin: 0 auto;\n" .
            "  padding: 48px 20px;\n" .
            "}\n"
        );

        File::put(
            $directory.'/assets/js/app.js',
            "document.documentElement.setAttribute('data-theme', '{$slug}');\n"
        );

        File::put($directory.'/lang/en/theme.php', "<?php\n\nreturn [];\n");
        File::put($directory.'/lang/vi/theme.php', "<?php\n\nreturn [];\n");

        $readme = <<<MD
# {$input}

Generated frontend theme skeleton for Pagify.

## Next steps

1. Update theme metadata in `theme.json`.
2. Customize `pages/home.json`.
3. Add extra pages with `pages/{slug}.json` or `pages/{slug}/index.json`.
4. Register head/body nodes and dynamic resolvers in WSRE document format.
5. Add localized strings in `lang/en/theme.php` and `lang/vi/theme.php`.
6. Extend static assets in `assets/js`, `assets/css`, and `assets/img`.

## Runtime notes

- Frontend runtime resolves pages in order: active theme -> fallback theme -> default theme.
- Homepage is loaded from `pages/home.json` (or `pages/index.json` as fallback).
- Theme is runtime-usable when `theme.json` is valid and `render.engine` is `wsre`.
MD;

        File::put($directory.'/README.md', $readme.PHP_EOL);

        $this->info(sprintf('Theme skeleton created at: %s', $directory));

        return self::SUCCESS;
    }
}
