<?php

namespace Pagify\Core\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class MakePluginCommand extends Command
{
    protected $signature = 'cms:make-plugin {name : Plugin name or slug}';

    protected $description = 'Generate Pagify plugin skeleton with plugin.json, migrations, permissions, and UI stubs.';

    public function handle(): int
    {
        $input = trim((string) $this->argument('name'));

        if ($input === '') {
            $this->error('Plugin name is required.');

            return self::INVALID;
        }

        $slug = Str::of($input)->slug('-')->toString();

        if ($slug === '') {
            $this->error('Unable to derive a valid plugin slug from input.');

            return self::INVALID;
        }

        $studly = Str::of($slug)->replace('-', ' ')->title()->replace(' ', '')->toString();
        $directory = base_path('plugins/'.$slug);

        if (is_dir($directory)) {
            $this->error(sprintf('Plugin directory already exists: %s', $directory));

            return self::FAILURE;
        }

        File::ensureDirectoryExists($directory.'/src/Providers');
        File::ensureDirectoryExists($directory.'/database/migrations');
        File::ensureDirectoryExists($directory.'/resources/js');
        File::ensureDirectoryExists($directory.'/config');

        $manifest = [
            'slug' => $slug,
            'name' => Str::of($input)->headline()->toString(),
            'version' => '0.1.0',
            'description' => 'Pagify plugin generated by cms:make-plugin.',
            'requires' => [
                'php' => '>=8.2',
                'laravel' => '^12.0',
                'core' => '^1.0',
            ],
            'providers' => [
                sprintf('Plugins\\%s\\Providers\\PluginServiceProvider', $studly),
            ],
            'hooks' => [
                'subscribers' => [],
            ],
            'ui' => [
                'menu' => [],
            ],
            'migrations' => [],
            'permissions' => [
                sprintf('plugin.%s.manage', str_replace('-', '.', $slug)),
            ],
            'extension_points' => [
                'field_types' => [],
                'blocks' => [],
                'dashboard_widgets' => [],
                'automation_actions' => [],
                'menu_items' => [],
            ],
        ];

        File::put(
            $directory.'/plugin.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
        );

        $providerContent = <<<PHP
<?php

namespace Plugins\\{$studly}\\Providers;

use Illuminate\\Support\\ServiceProvider;

class PluginServiceProvider extends ServiceProvider
{
    public function register(): void
    {
    }

    public function boot(): void
    {
    }
}
PHP;

        File::put($directory.'/src/Providers/PluginServiceProvider.php', $providerContent.PHP_EOL);

        $readme = <<<MD
# {$input}

Generated plugin skeleton for Pagify.

## Next steps

1. Update `plugin.json` metadata and compatibility constraints.
2. Implement provider logic in `src/Providers/PluginServiceProvider.php`.
3. Add migrations and extension contributions as needed.
MD;

        File::put($directory.'/README.md', $readme.PHP_EOL);

        $this->info(sprintf('Plugin skeleton created at: %s', $directory));

        return self::SUCCESS;
    }
}
