<?php

namespace Pagify\Core\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class MakeThemeCommand extends Command
{
    protected $signature = 'cms:make-theme {name : Theme name or slug}';

    protected $description = 'Generate Pagify frontend theme skeleton in themes/main/{slug}.';

    public function handle(): int
    {
        $input = trim((string) $this->argument('name'));

        if ($input === '') {
            $this->error('Theme name is required.');

            return self::INVALID;
        }

        $slug = Str::of($input)->slug('-')->toString();

        if ($slug === '') {
            $this->error('Unable to derive a valid theme slug from input.');

            return self::INVALID;
        }

        $directory = base_path('themes/main/'.$slug);

        if (is_dir($directory)) {
            $this->error(sprintf('Theme directory already exists: %s', $directory));

            return self::FAILURE;
        }

        File::ensureDirectoryExists($directory.'/resources/views/layouts');
        File::ensureDirectoryExists($directory.'/resources/views/pages');
        File::ensureDirectoryExists($directory.'/lang/en');
        File::ensureDirectoryExists($directory.'/lang/vi');

        $manifest = [
            'slug' => $slug,
            'name' => Str::of($input)->headline()->toString(),
            'version' => '1.0.0',
            'description' => 'Pagify frontend theme generated by cms:make-theme.',
            'author' => 'Community',
            'requires' => [
                'php' => '>=8.2',
                'laravel' => '^12.0',
            ],
            'supports' => [
                'pagify' => '^1.0',
            ],
        ];

        File::put(
            $directory.'/theme.json',
            json_encode($manifest, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES).PHP_EOL
        );

        $layout = <<<'BLADE'
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@yield('title', 'Pagify')</title>
    @yield('head')
</head>
<body>
    @yield('content')
</body>
</html>
BLADE;

        $page = <<<'BLADE'
@extends('layouts.app')

@section('head')
    {!! $head ?? '' !!}
@endsection

@section('content')
    {!! $content ?? '' !!}
@endsection
BLADE;

        File::put($directory.'/resources/views/layouts/app.blade.php', $layout.PHP_EOL);
        File::put($directory.'/resources/views/pages/page.blade.php', $page.PHP_EOL);
        File::put($directory.'/lang/en/theme.php', "<?php\n\nreturn [];\n");
        File::put($directory.'/lang/vi/theme.php', "<?php\n\nreturn [];\n");

        $readme = <<<MD
# {$input}

Generated frontend theme skeleton for Pagify.

## Next steps

1. Update theme metadata in `theme.json`.
2. Customize `resources/views/layouts/app.blade.php`.
3. Customize `resources/views/pages/page.blade.php`.
4. Add localized strings in `lang/en/theme.php` and `lang/vi/theme.php`.
MD;

        File::put($directory.'/README.md', $readme.PHP_EOL);

        $this->info(sprintf('Theme skeleton created at: %s', $directory));

        return self::SUCCESS;
    }
}
