<?php

return [
	'breakpoints' => ['desktop', 'tablet', 'mobile'],

	'editor' => [
		'simplified_mode' => true,
		'load_active_theme_styles' => true,
		'primary_blocks' => [
			'hero-banner',
			'columns-2',
			'image',
			'paragraph',
			'button',
			'stats-row',
			'feature-checklist',
			'logo-cloud',
			'cta-panel',
			'pricing-table',
			'contact-form',
		],
	],

	'webstudio_iframe' => [
		'enabled' => (bool) env('PAGE_BUILDER_IFRAME_EDITOR_ENABLED', false),
		'url' => (string) env('PAGE_BUILDER_IFRAME_EDITOR_URL', ''),
		'origin' => (string) env('PAGE_BUILDER_IFRAME_EDITOR_ORIGIN', ''),
		'token_ttl_seconds' => (int) env('PAGE_BUILDER_IFRAME_EDITOR_TOKEN_TTL', 300),
		'token_issuer' => (string) env('PAGE_BUILDER_IFRAME_EDITOR_TOKEN_ISSUER', (string) env('APP_URL', 'pagify')),
		'token_audience' => (string) env('PAGE_BUILDER_IFRAME_EDITOR_TOKEN_AUDIENCE', 'webstudio-editor'),
		'token_secret' => (string) env('PAGE_BUILDER_IFRAME_EDITOR_TOKEN_SECRET', ''),
		'token_replay_protection' => (bool) env('PAGE_BUILDER_IFRAME_EDITOR_TOKEN_REPLAY_PROTECTION', true),
		'token_replay_cache_prefix' => (string) env('PAGE_BUILDER_IFRAME_EDITOR_TOKEN_REPLAY_PREFIX', 'page-builder:editor-token-jti:'),
	],

	'webstudio_iframe_contract' => [
		'protocol_version' => 1,
		'namespace' => 'pagify:editor',
		'messages' => [
			'parent_to_child' => [
				'init' => 'pagify:editor:init',
				'set_layout' => 'pagify:editor:set-layout',
				'flush' => 'pagify:editor:flush',
				'search' => 'pagify:editor:search',
				'token_refresh_result' => 'pagify:editor:token-refresh-result',
			],
			'child_to_parent' => [
				'ready' => 'pagify:editor:ready',
				'error' => 'pagify:editor:error',
				'layout_change' => 'pagify:editor:layout-change',
				'token_refresh_request' => 'pagify:editor:token-refresh-request',
			],
			'host_events' => [
				'flush_request' => 'pbx-editor-flush',
				'search_request' => 'pbx-editor-search:set',
			],
		],
	],

	'permissions' => [
		'page-builder.page.viewAny',
		'page-builder.page.view',
		'page-builder.page.create',
		'page-builder.page.update',
		'page-builder.page.delete',
		'page-builder.page.publish',
		'page-builder.library.manage',
	],

	'internal_blocks' => [
		[
			'key' => 'heading',
			'label' => 'Heading',
			'icon' => '🔠',
			'category' => 'Typography',
			'description' => 'Section heading with supporting paragraph.',
			'html_template' => '<section class="pbx-section"><h2 class="pbx-heading">Build beautiful pages faster</h2><p class="pbx-text">Use this heading block to introduce your section with a clear message.</p></section>',
		],
		[
			'key' => 'paragraph',
			'label' => 'Paragraph',
			'icon' => '📝',
			'category' => 'Typography',
			'description' => 'Readable paragraph block for article-like content.',
			'html_template' => '<section class="pbx-section"><p class="pbx-text">Create rich, readable content with clean spacing and typography. This paragraph block is optimized for desktop, tablet, and mobile.</p></section>',
		],
		[
			'key' => 'button',
			'label' => 'Button',
			'icon' => '🔘',
			'category' => 'Actions',
			'description' => 'Primary call-to-action button.',
			'html_template' => '<section class="pbx-section"><a class="pbx-btn" href="#">Get started</a></section>',
		],
		[
			'key' => 'image',
			'label' => 'Image',
			'icon' => '🖼️',
			'category' => 'Media',
			'description' => 'Responsive image with optional caption.',
			'html_template' => '<figure class="pbx-section"><img class="pbx-image" src="https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1400&q=80" alt="Modern workspace" /><figcaption class="pbx-caption">Add a short caption to explain the visual.</figcaption></figure>',
		],
		[
			'key' => 'columns-2',
			'label' => '2 Columns',
			'icon' => '🧱',
			'category' => 'Layout',
			'description' => 'Two responsive columns that stack on mobile.',
			'html_template' => '<section class="pbx-section pbx-columns pbx-columns-2"><div class="pbx-card"><h3 class="pbx-subheading">Left column</h3><p class="pbx-text">Highlight feature, value, or supporting details here.</p></div><div class="pbx-card"><h3 class="pbx-subheading">Right column</h3><p class="pbx-text">Use the second column for comparison or another message.</p></div></section>',
		],
		[
			'key' => 'columns-3',
			'label' => '3 Columns',
			'icon' => '🧩',
			'category' => 'Layout',
			'description' => 'Three-column responsive layout for summaries.',
			'html_template' => '<section class="pbx-section pbx-columns pbx-columns-3"><div class="pbx-card"><h3 class="pbx-subheading">Column 1</h3><p class="pbx-text">Short supporting content.</p></div><div class="pbx-card"><h3 class="pbx-subheading">Column 2</h3><p class="pbx-text">Short supporting content.</p></div><div class="pbx-card"><h3 class="pbx-subheading">Column 3</h3><p class="pbx-text">Short supporting content.</p></div></section>',
		],
		[
			'key' => 'video-embed',
			'label' => 'Video',
			'icon' => '🎬',
			'category' => 'Media',
			'description' => 'Responsive 16:9 iframe video embed block.',
			'html_template' => '<section class="pbx-section"><div class="pbx-video"><iframe src="https://www.youtube.com/embed/dQw4w9WgXcQ" title="Video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe></div></section>',
		],
		[
			'key' => 'link-card',
			'label' => 'Link Card',
			'icon' => '🔗',
			'category' => 'Actions',
			'description' => 'Clickable card for navigation and highlights.',
			'html_template' => '<section class="pbx-section"><a href="#" class="pbx-link-card"><span class="pbx-link-card__eyebrow">Resource</span><span class="pbx-link-card__title">Read full documentation</span><span class="pbx-link-card__desc">Guide users to important content with one elegant card.</span></a></section>',
		],
		[
			'key' => 'card-grid',
			'label' => 'Card Grid',
			'icon' => '🔲',
			'category' => 'Layout',
			'description' => 'Responsive grid for products, services, or features.',
			'html_template' => '<section class="pbx-section pbx-grid"><article class="pbx-card"><h3 class="pbx-subheading">Starter</h3><p class="pbx-text">Great for small projects.</p></article><article class="pbx-card"><h3 class="pbx-subheading">Pro</h3><p class="pbx-text">For growing teams and traffic.</p></article><article class="pbx-card"><h3 class="pbx-subheading">Enterprise</h3><p class="pbx-text">Advanced controls and scale.</p></article><article class="pbx-card"><h3 class="pbx-subheading">Custom</h3><p class="pbx-text">Tailored implementation support.</p></article></section>',
		],
		[
			'key' => 'hero-banner',
			'label' => 'Hero Banner',
			'icon' => '✨',
			'category' => 'Sections',
			'description' => 'Top-of-page hero with heading, text, and CTA.',
			'html_template' => '<section class="pbx-hero"><div><p class="pbx-eyebrow">Modern Page Builder</p><h1 class="pbx-hero__title">Design responsive experiences without code lock-in</h1><p class="pbx-hero__text">Everything remains plain HTML/CSS, so your team keeps full control over presentation and structure.</p><a href="#" class="pbx-btn">Start building</a></div></section>',
		],
		[
			'key' => 'stats-row',
			'label' => 'Stats Row',
			'icon' => '📊',
			'category' => 'Data',
			'description' => 'Key metrics displayed in a clean responsive row.',
			'html_template' => '<section class="pbx-section pbx-stats"><div class="pbx-stat"><strong>120K+</strong><span>Monthly visitors</span></div><div class="pbx-stat"><strong>4.9/5</strong><span>User rating</span></div><div class="pbx-stat"><strong>99.95%</strong><span>Uptime SLA</span></div></section>',
		],
		[
			'key' => 'testimonial',
			'label' => 'Testimonial',
			'icon' => '💬',
			'category' => 'Social Proof',
			'description' => 'Customer quote with author and role.',
			'html_template' => '<section class="pbx-section"><blockquote class="pbx-quote">“Pagify helped us cut page build time in half while keeping full design freedom.”<cite><span>Lan Nguyen</span><small>Product Lead, Nova Team</small></cite></blockquote></section>',
		],
		[
			'key' => 'cta-panel',
			'label' => 'CTA Panel',
			'icon' => '🚀',
			'category' => 'Sections',
			'description' => 'High-contrast call-to-action panel.',
			'html_template' => '<section class="pbx-cta"><h2 class="pbx-cta__title">Ready to launch your next page?</h2><p class="pbx-cta__text">Use this panel near the bottom to drive your primary conversion action.</p><a class="pbx-btn pbx-btn--light" href="#">Book a demo</a></section>',
		],
		[
			'key' => 'site-header',
			'label' => 'Header',
			'icon' => '🧭',
			'category' => 'Sections',
			'description' => 'Responsive top navigation header with CTA.',
			'html_template' => '<header class="pbx-header"><div class="pbx-header__inner"><a href="#" class="pbx-header__brand">BrandName</a><nav class="pbx-header__nav"><a href="#">Home</a><a href="#">Features</a><a href="#">Pricing</a><a href="#">Contact</a></nav><a href="#" class="pbx-btn">Get started</a></div></header>',
		],
		[
			'key' => 'site-footer',
			'label' => 'Footer',
			'icon' => '🦶',
			'category' => 'Sections',
			'description' => 'Multi-column footer with links and copyright.',
			'html_template' => '<footer class="pbx-footer"><div class="pbx-footer__grid"><div><h3>BrandName</h3><p>Build faster with complete HTML/CSS freedom.</p></div><div><h4>Product</h4><a href="#">Features</a><a href="#">Pricing</a><a href="#">Integrations</a></div><div><h4>Company</h4><a href="#">About</a><a href="#">Blog</a><a href="#">Careers</a></div><div><h4>Support</h4><a href="#">Help center</a><a href="#">Status</a><a href="#">Contact</a></div></div><div class="pbx-footer__meta">© 2026 BrandName. All rights reserved.</div></footer>',
		],
		[
			'key' => 'pricing-table',
			'label' => 'Pricing',
			'icon' => '💵',
			'category' => 'Commerce',
			'description' => 'Responsive pricing cards with highlighted plan.',
			'html_template' => '<section class="pbx-section pbx-pricing"><article class="pbx-pricing-card"><h3>Starter</h3><p class="pbx-pricing-card__price">$19<span>/mo</span></p><ul><li>1 site</li><li>Basic analytics</li><li>Email support</li></ul><a href="#" class="pbx-btn">Choose starter</a></article><article class="pbx-pricing-card pbx-pricing-card--featured"><span class="pbx-pricing-card__badge">Popular</span><h3>Pro</h3><p class="pbx-pricing-card__price">$49<span>/mo</span></p><ul><li>5 sites</li><li>Advanced analytics</li><li>Priority support</li></ul><a href="#" class="pbx-btn">Choose pro</a></article><article class="pbx-pricing-card"><h3>Scale</h3><p class="pbx-pricing-card__price">$99<span>/mo</span></p><ul><li>Unlimited sites</li><li>Custom reports</li><li>Dedicated success</li></ul><a href="#" class="pbx-btn">Choose scale</a></article></section>',
		],
		[
			'key' => 'faq-list',
			'label' => 'FAQ',
			'icon' => '❓',
			'category' => 'Support',
			'description' => 'Accordion-style FAQ list using semantic details elements.',
			'html_template' => '<section class="pbx-section pbx-faq"><h2 class="pbx-heading">Frequently asked questions</h2><details open><summary>Can I use custom HTML/CSS?</summary><p>Yes. You can edit every block directly and keep full design control.</p></details><details><summary>Does it work on mobile devices?</summary><p>All blocks are responsive by default and adapt to smaller screens.</p></details><details><summary>Can I save reusable sections?</summary><p>Yes, save sections into your library and insert them across pages.</p></details></section>',
		],
		[
			'key' => 'contact-form',
			'label' => 'Contact Form',
			'icon' => '📨',
			'category' => 'Forms',
			'description' => 'Responsive contact form section with modern inputs.',
			'html_template' => '<section class="pbx-section pbx-contact"><div class="pbx-contact__intro"><h2 class="pbx-heading">Let’s talk about your project</h2><p class="pbx-text">Send your requirements and our team will get back within one business day.</p></div><form class="pbx-contact__form"><label>Full name<input type="text" name="name" placeholder="Your name" /></label><label>Email<input type="email" name="email" placeholder="you@example.com" /></label><label>Message<textarea name="message" rows="4" placeholder="How can we help?"></textarea></label><button type="submit" class="pbx-btn">Send message</button></form></section>',
		],
		[
			'key' => 'feature-checklist',
			'label' => 'Feature Checklist',
			'icon' => '✅',
			'category' => 'Sections',
			'description' => 'Popular checklist-style section for key product benefits.',
			'html_template' => '<section class="pbx-section"><h2 class="pbx-heading">Everything you need to launch faster</h2><ul class="pbx-text"><li>Reusable section library for consistent pages</li><li>Responsive blocks optimized for desktop and mobile</li><li>Fast publishing workflow with draft/live states</li><li>Built-in SEO controls for title and metadata</li></ul></section>',
		],
		[
			'key' => 'logo-cloud',
			'label' => 'Logo Cloud',
			'icon' => '🏷️',
			'category' => 'Social Proof',
			'description' => 'Common trust section to showcase customer or partner logos.',
			'html_template' => '<section class="pbx-section"><p class="pbx-eyebrow">Trusted by leading teams</p><div class="pbx-grid"><div class="pbx-card"><p class="pbx-subheading">Nova</p></div><div class="pbx-card"><p class="pbx-subheading">Helio</p></div><div class="pbx-card"><p class="pbx-subheading">Atlas</p></div><div class="pbx-card"><p class="pbx-subheading">Orbit</p></div></div></section>',
		],
		[
			'key' => 'process-steps',
			'label' => 'Process Steps',
			'icon' => '🪜',
			'category' => 'Sections',
			'description' => 'Three-step process block for onboarding or conversion flow.',
			'html_template' => '<section class="pbx-section"><h2 class="pbx-heading">How it works</h2><div class="pbx-columns pbx-columns-3"><article class="pbx-card"><p class="pbx-eyebrow">Step 1</p><h3 class="pbx-subheading">Set up your page</h3><p class="pbx-text">Choose a layout and drag blocks into the content area.</p></article><article class="pbx-card"><p class="pbx-eyebrow">Step 2</p><h3 class="pbx-subheading">Customize content</h3><p class="pbx-text">Update text, links, and visuals to match your campaign.</p></article><article class="pbx-card"><p class="pbx-eyebrow">Step 3</p><h3 class="pbx-subheading">Publish with confidence</h3><p class="pbx-text">Review, save changes, and publish when ready.</p></article></div></section>',
		],
		[
			'key' => 'team-cards',
			'label' => 'Team Cards',
			'icon' => '🧑‍🤝‍🧑',
			'category' => 'Social Proof',
			'description' => 'Popular team introduction section with role summaries.',
			'html_template' => '<section class="pbx-section"><h2 class="pbx-heading">Meet the team</h2><div class="pbx-grid"><article class="pbx-card"><h3 class="pbx-subheading">Lan Nguyen</h3><p class="pbx-caption">Product Lead</p><p class="pbx-text">Guides product direction and customer value.</p></article><article class="pbx-card"><h3 class="pbx-subheading">An Tran</h3><p class="pbx-caption">Engineering Manager</p><p class="pbx-text">Leads platform architecture and delivery quality.</p></article><article class="pbx-card"><h3 class="pbx-subheading">Minh Pham</h3><p class="pbx-caption">Growth Specialist</p><p class="pbx-text">Optimizes acquisition funnels and campaign performance.</p></article></div></section>',
		],
		[
			'key' => 'newsletter-signup',
			'label' => 'Newsletter Signup',
			'icon' => '📬',
			'category' => 'Forms',
			'description' => 'Quick email capture section for updates and promotions.',
			'html_template' => '<section class="pbx-cta"><h2 class="pbx-cta__title">Stay in the loop</h2><p class="pbx-cta__text">Get product updates and practical guides delivered weekly.</p><form class="pbx-contact__form"><label>Email address<input type="email" name="email" placeholder="you@example.com" /></label><button type="submit" class="pbx-btn">Subscribe</button></form></section>',
		],
		[
			'key' => 'content-card',
			'label' => 'Content Card',
			'icon' => '🗂️',
			'category' => 'Utility',
			'description' => 'Basic card container for flexible custom content.',
			'html_template' => '<section class="pbx-section"><article class="pbx-card"><h3 class="pbx-subheading">Card title</h3><p class="pbx-text">Use this card as a reusable content container for highlights, notes, or feature details.</p></article></section>',
		],
		[
			'key' => 'alert-box',
			'label' => 'Alert Box',
			'icon' => '🚨',
			'category' => 'Utility',
			'description' => 'Reusable alert for info, warning, or announcement messages.',
			'html_template' => '<section class="pbx-section"><div class="pbx-card" style="border-color:#fcd34d;background:#fffbeb;"><p class="pbx-eyebrow" style="color:#92400e;">Notice</p><p class="pbx-text" style="color:#78350f;">This is an important message. Update text and colors to match your context.</p></div></section>',
		],
		[
			'key' => 'badge-row',
			'label' => 'Badge Row',
			'icon' => '🏷️',
			'category' => 'Utility',
			'description' => 'Small label chips for tags, skills, or status lists.',
			'html_template' => '<section class="pbx-section"><div style="display:flex;flex-wrap:wrap;gap:8px;"><span style="display:inline-flex;align-items:center;padding:6px 10px;border-radius:999px;background:#ede9fe;color:#5b21b6;font-size:12px;font-weight:600;">Design</span><span style="display:inline-flex;align-items:center;padding:6px 10px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-size:12px;font-weight:600;">Marketing</span><span style="display:inline-flex;align-items:center;padding:6px 10px;border-radius:999px;background:#dcfce7;color:#166534;font-size:12px;font-weight:600;">Product</span></div></section>',
		],
		[
			'key' => 'divider-line',
			'label' => 'Divider',
			'icon' => '➖',
			'category' => 'Utility',
			'description' => 'Horizontal divider to separate content sections clearly.',
			'html_template' => '<section class="pbx-section" style="padding-top:10px;padding-bottom:10px;"><hr style="border:0;border-top:1px solid #e2e8f0;margin:0;"></section>',
		],
		[
			'key' => 'spacer-block',
			'label' => 'Spacer',
			'icon' => '↕️',
			'category' => 'Utility',
			'description' => 'Adjust vertical spacing between blocks with a neutral spacer.',
			'html_template' => '<section class="pbx-section" style="padding-top:0;padding-bottom:0;"><div style="height:32px;"></div></section>',
		],
		[
			'key' => 'bullet-list',
			'label' => 'Bullet List',
			'icon' => '📋',
			'category' => 'Typography',
			'description' => 'Simple bulleted list for requirements or key takeaways.',
			'html_template' => '<section class="pbx-section"><h3 class="pbx-subheading">Key points</h3><ul class="pbx-text" style="padding-left:20px;"><li>First important point</li><li>Second important point</li><li>Third important point</li></ul></section>',
		],
		[
			'key' => 'quote-callout',
			'label' => 'Quote Callout',
			'icon' => '🗨️',
			'category' => 'Utility',
			'description' => 'Compact quote block for notable statements or highlights.',
			'html_template' => '<section class="pbx-section"><blockquote class="pbx-quote" style="padding:16px 18px;"><p style="margin:0;">“Use this callout to emphasize a key insight or statement.”</p><cite><span>Author name</span><small>Role or source</small></cite></blockquote></section>',
		],
		[
			'key' => 'form-input-row',
			'label' => 'Form Input Row',
			'icon' => '⌨️',
			'category' => 'Forms',
			'description' => 'Single labeled input row for quick form composition.',
			'html_template' => '<section class="pbx-section"><form class="pbx-contact__form"><label>Full name<input type="text" name="full_name" placeholder="Your full name" /></label></form></section>',
		],
		[
			'key' => 'form-two-field-row',
			'label' => 'Form Two-Field Row',
			'icon' => '🧾',
			'category' => 'Forms',
			'description' => 'Two-column row for email/phone or similar paired fields.',
			'html_template' => '<section class="pbx-section"><form class="pbx-contact__form"><div class="pbx-columns pbx-columns-2"><label>Email<input type="email" name="email" placeholder="you@example.com" /></label><label>Phone<input type="tel" name="phone" placeholder="+84" /></label></div></form></section>',
		],
		[
			'key' => 'form-consent-checkbox',
			'label' => 'Consent Checkbox',
			'icon' => '☑️',
			'category' => 'Forms',
			'description' => 'Consent row for policy agreement before submit.',
			'html_template' => '<section class="pbx-section" style="padding-top:6px;padding-bottom:6px;"><form class="pbx-contact__form"><label style="display:flex;align-items:flex-start;gap:8px;"><input type="checkbox" name="consent" style="margin-top:3px;" /><span class="pbx-text" style="margin:0;">I agree to the privacy policy and terms of service.</span></label></form></section>',
		],
		[
			'key' => 'form-submit-row',
			'label' => 'Form Submit Row',
			'icon' => '📨',
			'category' => 'Forms',
			'description' => 'Submit action row with helper text for conversion forms.',
			'html_template' => '<section class="pbx-section" style="padding-top:6px;"><form class="pbx-contact__form"><div style="display:flex;flex-wrap:wrap;gap:10px;align-items:center;"><button type="submit" class="pbx-btn">Submit form</button><p class="pbx-caption" style="margin:0;">We usually reply within one business day.</p></div></form></section>',
		],
	],

	'default_page_templates' => [
		[
			'slug' => 'landing',
			'name' => 'Landing',
			'category' => 'landing',
			'description' => 'Simple conversion-focused landing layout.',
			'schema_json' => [
				'sections' => [
					[
						'id' => 'hero',
						'blocks' => [
							['type' => 'heading', 'props' => ['text' => 'Landing headline']],
							['type' => 'paragraph', 'props' => ['text' => 'Landing page subtitle']],
							['type' => 'button', 'props' => ['label' => 'Start now', 'href' => '#']],
						],
					],
				],
			],
		],
		[
			'slug' => 'blog',
			'name' => 'Blog',
			'category' => 'blog',
			'description' => 'Header, posts list and CTA.',
			'schema_json' => [
				'sections' => [
					[
						'id' => 'intro',
						'blocks' => [
							['type' => 'heading', 'props' => ['text' => 'Blog title']],
							['type' => 'paragraph', 'props' => ['text' => 'Latest insights and stories.']],
						],
					],
				],
			],
		],
		[
			'slug' => 'docs',
			'name' => 'Docs',
			'category' => 'docs',
			'description' => 'Documentation layout starter.',
			'schema_json' => [
				'sections' => [
					[
						'id' => 'docs-intro',
						'blocks' => [
							['type' => 'heading', 'props' => ['text' => 'Documentation']],
							['type' => 'paragraph', 'props' => ['text' => 'Write guides for your users.']],
						],
					],
				],
			],
		],
		[
			'slug' => 'portfolio',
			'name' => 'Portfolio',
			'category' => 'portfolio',
			'description' => 'Portfolio showcase starter.',
			'schema_json' => [
				'sections' => [
					[
						'id' => 'portfolio-hero',
						'blocks' => [
							['type' => 'heading', 'props' => ['text' => 'Featured work']],
							['type' => 'paragraph', 'props' => ['text' => 'Highlight your best projects.']],
						],
					],
				],
			],
		],
	],
];
